### ISSUE TITLE
Small Blessing: Wish for Peace does not end combat immediately

### ISSUE THREAD

**Issue by amonSul** [dewkid/RealmSpeak#12]
Reproduce:
- Start as the Pilgrim at the Chapel
- Cast Small Blessing during combat (I think it was second round and the lancers were present, but had rolled a NO DEAL)
- Roll "I wish for peace"
- Combat should end immediately but continued for another two rounds

Extract from Log:

> RealmBattle - =======================
> RealmBattle - Evening of month 1, day 1, in clearing Dark Valley 5
> RealmBattle - -----------------------
> RealmBattle - --  Combat Round 1
> RealmBattle - -----------------------
> RealmBattle -  - - - - - Luring
> RealmBattle -  - - - - - Deployment
> RealmBattle -  - - - - - Actions
> RealmBattle -  - - - - - Assign Targets
> RealmBattle - Assigning random target selection order.
> RealmBattle -  - - - - - Positioning
> RealmBattle -  - - - - - Reposition/Tactics
> RealmBattle -  - - - - - Resolve Combat
> RealmBattle - Attacks are sorted by LENGTH first, then by SPEED.
> RealmBattle - ---- DISENGAGEMENT ----
> RealmBattle - 1 consecutive round of no damage, fatigue, or spellcasting.
> RealmBattle - -----------------------
> RealmBattle - --  Combat Round 2
> RealmBattle - -----------------------
> RealmBattle -  - - - - - Luring
> RealmBattle -  - - - - - Deployment
> RealmBattle -  - - - - - Actions
> Pilgrim - Casts Small Blessing
> Pilgrim - Burns a White chit.
> Pilgrim - Fatigued color chit: MAGIC I6*
> RealmBattle -  - - - - - Assign Targets
> RealmBattle - Assigning random target selection order.
> Pilgrim - Targets the Pilgrim () with Small Blessing
> RealmBattle -  - - - - - Positioning
> Pilgrim - Wish roll: Rolled 4 (red) and 4 (white).
> Pilgrim - Wish result: I wish for peace
> Pilgrim - Fatigued chit: MAGIC I4*
> RealmBattle -  - - - - - Reposition/Tactics
> RealmBattle -  - - - - - Resolve Combat
> RealmBattle - Attacks are sorted by SPEED first, then by LENGTH.
> RealmBattle - ---- DISENGAGEMENT ----
> RealmBattle - -----------------------
> RealmBattle - --  Combat Round 3
> RealmBattle - -----------------------
> RealmBattle -  - - - - - Luring
> RealmBattle -  - - - - - Deployment
> RealmBattle -  - - - - - Actions
> RealmBattle -  - - - - - Assign Targets
> RealmBattle - Assigning random target selection order.
> RealmBattle -  - - - - - Positioning
> RealmBattle -  - - - - - Reposition/Tactics
> RealmBattle -  - - - - - Resolve Combat
> RealmBattle - Attacks are sorted by SPEED first, then by LENGTH.
> RealmBattle - ---- DISENGAGEMENT ----
> RealmBattle - 1 consecutive round of no damage, fatigue, or spellcasting.
> RealmBattle - -----------------------
> RealmBattle - --  Combat Round 4
> RealmBattle - -----------------------
> RealmBattle -  - - - - - Luring
> RealmBattle -  - - - - - Deployment
> RealmBattle -  - - - - - Actions
> RealmBattle -  - - - - - Assign Targets
> RealmBattle - Assigning random target selection order.
> RealmBattle -  - - - - - Positioning
> RealmBattle -  - - - - - Reposition/Tactics
> RealmBattle -  - - - - - Resolve Combat
> RealmBattle - Attacks are sorted by SPEED first, then by LENGTH.
> RealmSpeak - ========================================
> RealmSpeak - Month 1, Day 2
> RealmSpeak - ========================================
> RealmBattle - ---- DISENGAGEMENT ----
> RealmBattle - 2 consecutive rounds of no damage, fatigue, or spellcasting.
> Pilgrim - Spent the night at the Chapel.

**Comment by danielt1263** [comment]
Not a bug. The rules specifically say that two rounds should happen after the spell is cast.

**Comment by amonSul** [comment]
4. Rounds of combat continue for two rounds to allow characters to do actions. This “peace” cannot be broken before it expires.

My bad. Thank you for pointing this out.

**Comment by amonSul** [comment]
Cheers DanielT. Are you aware there is a RS session starting?
https://docs.google.com/forms/d/e/1FAIpQLSejmhNe7hLqgrCWQvct7vPJS2DjvU-7oXzY_rguSDKql4JG7w/viewform?vc=0&amp;c=0&amp;w=1&amp;usp=mail_form_link
